counter = [0] * 26

f = open("Sample.txt", "r" ,encoding='utf-8')
lines = f.readlines()  
for line in lines:　
 counter[0] += line.count('a') + line.count('A')
    counter[1] += line.count('b') + line.count('B')
    counter[2] += line.count('c') + line.count('C')
    counter[3] += line.count('d') + line.count('D')
    counter[4] += line.count('e') + line.count('E')
    counter[5] += line.count('f') + line.count('F')
    counter[6] += line.count('g') + line.count('G')
    counter[7] += line.count('h') + line.count('H')
    counter[8] += line.count('i') + line.count('I')
    counter[9] += line.count('j') + line.count('J')
    counter[10] += line.count('K') + line.count('K')
    counter[11] += line.count('l') + line.count('L')
    counter[12] += line.count('m') + line.count('M')
    counter[13] += line.count('n') + line.count('N')
    counter[14] += line.count('o') + line.count('O')
    counter[15] += line.count('p') + line.count('P')
    counter[16] += line.count('q') + line.count('Q')
    counter[17] += line.count('r') + line.count('R')
    counter[18] += line.count('s') + line.count('S')
    counter[19] += line.count('t') + line.count('T')
    counter[20] += line.count('u') + line.count('U')
    counter[21] += line.count('v') + line.count('V')
    counter[22] += line.count('w') + line.count('W')
    counter[23] += line.count('x') + line.count('X')
    counter[24] += line.count('y') + line.count('Y')
    counter[25] += line.count('z') + line.count('Z')

f.close()

sum = 0

for i in counter:
    sum += i
    
print(counter)
print()

print("a =",counter[0])
print("b =",counter[1])
print("c =",counter[2])
print("d =",counter[3])
print("e =",counter[4])
print("f =",counter[5])
print("g =",counter[6])
print("h =",counter[7])
print("i =",counter[8])
print("j =",counter[9])
print("k =",counter[10])
print("l =",counter[11])
print("m =",counter[12])
print("n =",counter[13])
print("o =",counter[14])
print("p =",counter[15])
print("q =",counter[16])
print("r =",counter[17])
print("s =",counter[18])
print("t =",counter[19])
print("u =",counter[20])
print("v =",counter[21])
print("w =",counter[22])
print("x =",counter[23])
print("y =",counter[24])
print("z =",counter[25])

print()
print("合計文字数=",sum)
